-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
ID_Cliente INTEGER PRIMARY KEY,
Sexo CHAR(1),
Nome VARCHAR(50),
CPF CHAR(11)
)


CREATE TABLE PRODUTO (
ID_Produto INTEGER PRIMARY KEY,
VL_Unitario NUMERIC(5,2),
Descricao VARCHAR(50),
DT_Validade DATE,
DT_Fabricacao DATE,
Lote INTEGER,
QTD_Estoque INTEGER,
Marca VARCHAR(30)
)

CREATE TABLE FORMA_PAGTO (
ID_Forma_Pagto INTEGER PRIMARY KEY,
Descricao VARCHAR(30)
)

CREATE TABLE COMPRA_PRODUTO (
ID_Compra_Produto INTEGER PRIMARY KEY,
QTD_Comprada INTEGER,
VL_Total_Item NUMERIC(7,2),
ID_Produto INTEGER,
FOREIGN KEY(ID_Produto) REFERENCES PRODUTO (ID_Produto)
)

CREATE TABLE COMPRA (
ID_Compra INTEGER PRIMARY KEY,
DT_Compra DATE,
VL_Total_Compra NUMERIC(7,2),
Atendente VARCHAR(50),
ID_Forma_Pagto INTEGER,
ID_Cliente INTEGER,
ID_Compra_Produto INTEGER,
FOREIGN KEY(ID_Cliente) REFERENCES CLIENTE (ID_Cliente),
FOREIGN KEY(ID_Forma_Pagto) REFERENCES FORMA_PAGTO (ID_Forma_Pagto),
FOREIGN KEY(ID_Compra_Produto) REFERENCES COMPRA_PRODUTO (ID_Compra_Produto)
)