
package ifmt.cba.servico;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicoControleEstoque", targetNamespace = "http://servico.cba.ifmt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoControleEstoque {


    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalizarValorEstoqueProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalizarValorEstoqueProduto")
    @ResponseWrapper(localName = "totalizarValorEstoqueProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalizarValorEstoqueProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/totalizarValorEstoqueProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/totalizarValorEstoqueProdutoResponse")
    public float totalizarValorEstoqueProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProdutoVO arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "baixarEstoqueProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.BaixarEstoqueProduto")
    @ResponseWrapper(localName = "baixarEstoqueProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.BaixarEstoqueProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/baixarEstoqueProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/baixarEstoqueProdutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servico.cba.ifmt/ServicoControleEstoque/baixarEstoqueProduto/Fault/Exception")
    })
    public void baixarEstoqueProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProdutoVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ifmt.cba.servico.ProdutoVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarProdutoPorCodigo", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.BuscarProdutoPorCodigo")
    @ResponseWrapper(localName = "buscarProdutoPorCodigoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.BuscarProdutoPorCodigoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/buscarProdutoPorCodigoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/buscarProdutoPorCodigoResponse")
    public ProdutoVO buscarProdutoPorCodigo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalizarValorEstoqueGeral", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalizarValorEstoqueGeral")
    @ResponseWrapper(localName = "totalizarValorEstoqueGeralResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalizarValorEstoqueGeralResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/totalizarValorEstoqueGeralRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/totalizarValorEstoqueGeralResponse")
    public float totalizarValorEstoqueGeral();

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "adicionarEstoqueProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.AdicionarEstoqueProduto")
    @ResponseWrapper(localName = "adicionarEstoqueProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.AdicionarEstoqueProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarEstoqueProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarEstoqueProdutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarEstoqueProduto/Fault/Exception")
    })
    public void adicionarEstoqueProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProdutoVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "adicionarProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.AdicionarProduto")
    @ResponseWrapper(localName = "adicionarProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.AdicionarProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarProdutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servico.cba.ifmt/ServicoControleEstoque/adicionarProduto/Fault/Exception")
    })
    public void adicionarProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProdutoVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removerProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.RemoverProduto")
    @ResponseWrapper(localName = "removerProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.RemoverProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/removerProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/removerProdutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servico.cba.ifmt/ServicoControleEstoque/removerProduto/Fault/Exception")
    })
    public void removerProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProdutoVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalEstoqueFisico", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalEstoqueFisico")
    @ResponseWrapper(localName = "totalEstoqueFisicoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.TotalEstoqueFisicoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/totalEstoqueFisicoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/totalEstoqueFisicoResponse")
    public int totalEstoqueFisico();

    /**
     * 
     * @return
     *     returns java.util.List<ifmt.cba.servico.ProdutoVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.ListaProduto")
    @ResponseWrapper(localName = "listaProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.ListaProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/listaProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/listaProdutoResponse")
    public List<ProdutoVO> listaProduto();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "contadorProduto", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.ContadorProduto")
    @ResponseWrapper(localName = "contadorProdutoResponse", targetNamespace = "http://servico.cba.ifmt/", className = "ifmt.cba.servico.ContadorProdutoResponse")
    @Action(input = "http://servico.cba.ifmt/ServicoControleEstoque/contadorProdutoRequest", output = "http://servico.cba.ifmt/ServicoControleEstoque/contadorProdutoResponse")
    public int contadorProduto();

}
