
package ifmt.cba.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicoControleEstoqueImplService", targetNamespace = "http://servico.cba.ifmt/", wsdlLocation = "http://localhost:8083/servico/estoque/estoque?wsdl")
public class ServicoControleEstoqueImplService
    extends Service
{

    private static final URL SERVICOCONTROLEESTOQUEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVICOCONTROLEESTOQUEIMPLSERVICE_EXCEPTION;
    private static final QName SERVICOCONTROLEESTOQUEIMPLSERVICE_QNAME = new QName("http://servico.cba.ifmt/", "ServicoControleEstoqueImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/servico/estoque/estoque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOCONTROLEESTOQUEIMPLSERVICE_WSDL_LOCATION = url;
        SERVICOCONTROLEESTOQUEIMPLSERVICE_EXCEPTION = e;
    }

    public ServicoControleEstoqueImplService() {
        super(__getWsdlLocation(), SERVICOCONTROLEESTOQUEIMPLSERVICE_QNAME);
    }

    public ServicoControleEstoqueImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOCONTROLEESTOQUEIMPLSERVICE_QNAME, features);
    }

    public ServicoControleEstoqueImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICOCONTROLEESTOQUEIMPLSERVICE_QNAME);
    }

    public ServicoControleEstoqueImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOCONTROLEESTOQUEIMPLSERVICE_QNAME, features);
    }

    public ServicoControleEstoqueImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoControleEstoqueImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoControleEstoque
     */
    @WebEndpoint(name = "ServicoControleEstoqueImplPort")
    public ServicoControleEstoque getServicoControleEstoqueImplPort() {
        return super.getPort(new QName("http://servico.cba.ifmt/", "ServicoControleEstoqueImplPort"), ServicoControleEstoque.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoControleEstoque
     */
    @WebEndpoint(name = "ServicoControleEstoqueImplPort")
    public ServicoControleEstoque getServicoControleEstoqueImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.cba.ifmt/", "ServicoControleEstoqueImplPort"), ServicoControleEstoque.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOCONTROLEESTOQUEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICOCONTROLEESTOQUEIMPLSERVICE_EXCEPTION;
        }
        return SERVICOCONTROLEESTOQUEIMPLSERVICE_WSDL_LOCATION;
    }

}
